Repository SeattleColleges/nsc-events-nextjs, pull requests merged in 2023-07, with the labels that each got.

#9 Create pull_request_template.md
  docs/pull_request_template.md
Labels: Sprint 2

#8 Feature 5 langingpage 01
  app/api/auth/[...nextauth]/route.ts
  app/api/auth/forgot-password/page.tsx
  app/api/auth/profile/page.tsx
  app/api/auth/sign-in/page.tsx
  app/api/auth/sign-up/page.tsx
  app/api/auth/users/route.ts
  app/layout.tsx
  app/page.tsx
  components/InputFields.tsx
  components/Navbar.tsx
  components/SessionProvider.tsx
  package-lock.json
  package.json
  styles/Home.module.css
  styles/globals.css
Labels: Sprint 2

#18 Ci cd 7 jest unit testing
  .github/ci.yml
  jest.config.js
  package.json
  tests/mocks/math.ts
  tests/unit/math.test.ts
Labels: Sprint 2

#19 Ci cd 6 jest coverage
  .github/ci.yml
  docs/coverage/base.css
  docs/coverage/block-navigation.js
  docs/coverage/favicon.png
  docs/coverage/index.html
  docs/coverage/math.ts.html
  docs/coverage/prettify.css
  docs/coverage/prettify.js
  docs/coverage/sort-arrow-sprite.png
  docs/coverage/sorter.js
  package.json
Labels: Sprint 2

#26 Ci cd 7 added unit test
  tests/mocks/math.ts
  tests/unit/math.test.ts
Labels: Sprint 2

#28 Added .idea and .env files. Excluded .env.sample
  .gitignore
Labels: Sprint 2

#30 Revised ci cd workflow
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/main.yml
  package-lock.json
  tests/mocks/math.ts
Labels: Sprint 2

#34 Refactored CSS module #05
  app/api/auth/forgot-password/forget-password-page.module.css
  app/api/auth/forgot-password/page.tsx
  app/api/auth/sign-in/page.tsx
  app/api/auth/sign-in/signin-page.module.css
  app/api/auth/sign-up/page.tsx
  app/api/auth/sign-up/signup-page.module.css
  app/login-page.module.css
  app/page.tsx
Labels: enhancement, Sprint 2

#40 Refactor (commented out) profile page
  .github/workflows/ci.yml
  .github/workflows/staging.yml
  app/api/auth/forgot-password/forget-password-page.module.css
  app/api/auth/forgot-password/page.tsx
  app/api/auth/profile/page.tsx
  app/api/auth/sign-in/page.tsx
  app/api/auth/sign-in/signin-page.module.css
  app/api/auth/sign-up/page.tsx
  app/api/auth/sign-up/signup-page.module.css
  app/login-page.module.css
  app/page.tsx
Labels: Sprint 1
