Repository SeattleColleges/nsc-events-nextjs, pull requests merged in 2023-08, with the labels that each got.

#43 feat: created json object to represent an event.
  models/event-autofill.js
  models/event.js
Labels: Sprint 4

#41 Ci refactor standardize with naming in android
  .github/workflows/cd-production.yml
  .github/workflows/cd-staging.yml
  .github/workflows/ci.yml
  .github/workflows/on-new-branch.yml
  .github/workflows/on-pull-request.yml
  .github/workflows/on-push-staging.yml
  .github/workflows/sync-staging.yml
Labels: enhancement

#48 Feat 37 create event page 01
  app/create-event/page.tsx
  components/TagSelector.tsx
  models/activity.ts
  models/activityAutofill.ts
  models/event.js
Labels: Sprint 4

#46 Feat 38 begin web auth backend 01
  .env.sample
  lib/db.ts
  models/userModel.ts
  package-lock.json
  package.json
Labels: Sprint 4

#51 nsc-events-nextjs-5-50-finish-web-user-auth
  app/api/auth/[...nextauth]/route.ts
  app/api/auth/forgot-password/forget-password-page.module.css
  app/api/auth/sign-in/signin-page.module.css
  app/api/auth/sign-up/signup-page.module.css
  app/api/auth/users/route.ts
  app/auth/forgot-password/forgot-password-page.module.css
  app/auth/forgot-password/page.tsx
  app/auth/sign-in/page.tsx
  app/auth/sign-in/signin-page.module.css
  app/auth/sign-up/page.tsx
  app/auth/sign-up/signup-page.module.css
  app/layout.tsx
  app/page.tsx
  app/profile/page.tsx
  components/AuthProfileMenu.tsx
  components/Navbar.tsx
  package-lock.json
  package.json
Labels: Sprint 5

#61 nsc-events-nextJS_5_47_homepage-addition-UI-update
  app/auth/forgot-password/forgot-password-page.module.css
  app/auth/forgot-password/page.tsx
  app/auth/sign-in/page.tsx
  app/auth/sign-in/signin-page.module.css
  app/auth/sign-up/page.tsx
  app/auth/sign-up/signup-page.module.css
  app/google_play.png
  app/home.module.css
  app/login-page.module.css
  app/logo.png
  app/page.tsx
  components/AuthProfileMenu.tsx
  components/Navbar.tsx
Labels: Sprint 5

#64 Eslint rule change enforce object curly spacing
  .eslintrc.json
  app/api/auth/[...nextauth]/route.ts
  app/api/auth/users/route.ts
  app/auth/forgot-password/page.tsx
  app/create-event/page.tsx
  components/AuthProfileMenu.tsx
  components/SessionProvider.tsx
  lib/db.ts
  models/userModel.ts
  tests/unit/math.test.ts
Labels: documentation
