Repository SeattleColleges/nsc-events-nextjs, pull requests merged in 2024-03, with the labels that each got.

#233 nsc-events-nextjs_4_232_update-url
  app/auth/sign-in/page.tsx
  app/auth/sign-up/signupApi.tsx
  components/EventGetter.tsx
  next.config.js
Labels: enhancement, Sprint 4

#241 nsc-events-nextjs_4_240_delete_find_stale_templates
  docs/pull_request_template.md
Labels: bug, Sprint 4

#238 nsc-events-nextjs-4-237-create-event-functionality
  app/create-event/page.tsx
  hooks/useEventForm.tsx
  models/activity.ts
  models/activityAutofill.ts
  models/activityDatabase.ts
Labels: enhancement, Sprint 4, USER STORY

#235 nsc-events-nextjs-4-234-display-upcoming-events-section
  app/home.module.css
  app/page.tsx
  components/HomeEventGetter.tsx
  components/UpcomingEvent.tsx
Labels: Sprint 4

#244 nsc-events-nextjs _ 4 _ 243 _ change-password-page
  app/auth/change-password/changePasswordApi.tsx
  app/auth/change-password/page.tsx
  app/auth/change-password/validatePassword.tsx
Labels: enhancement, Sprint 4

#246 nsc-events-nextjs-4-245-sort-events-by-date
  components/HomeEventGetter.tsx
Labels: Sprint 4

#239 nsc-events-nextjs_4_230_add-delete-event-functionality
  app/event-detail/page.tsx
  components/EventGetter.tsx
  components/HomeEventGetter.tsx
  components/UpcomingEvent.tsx
  models/activityDatabase.ts
Labels: Sprint 4
