Repository SeattleColleges/nsc-events-nextjs, pull requests merged in 2024-06, with the labels that each got.

#373 nsc-events-nextjs_7_368_update_home_event_pagination_logic
  components/HomeEventGetter.tsx
  components/UpcomingEvent.tsx
  utility/queries.ts
Labels: Sprint 7

#367 NSC_NextJS_Sprint_7_357_Change_Edit_to_Done
  components/EditUserRoleDialog.tsx
  components/UserCard.tsx
Labels: Sprint 7

#391 nsc-nextjs-chore-add-deployed-api-url
  app/auth/sign-up/signupApi.tsx
  app/edit-user-role-page/page.tsx
  app/event-detail/page.tsx
  components/ArchiveDialog.tsx
  components/AttendDialog.tsx
  components/EditUserRoleDialog.tsx
  components/ViewMyEventsGetter.tsx
  hooks/useEditForm.tsx
  hooks/useEventForm.tsx
  next.config.js
  utility/queries.ts
Labels: Sprint 7

#387 Revert "nsc-events-nextjs_7_295_arrow_icons"
  app/event-detail/page.tsx
Labels: Sprint 7

#385 nsc-events-nextjs_7_379_nvmrc
  .nvmrc
  app/create-event/page.tsx
Labels: Sprint 7

#400 nsc-events-nextjs_8_399_admin_change-password-page_changes
  app/admin/page.tsx
  app/auth/change-password/page.tsx
Labels: enhancement, Sprint 8

#408 nsc-events-nextjs_8_401_logos_spacing
  app/auth/change-password/page.tsx
  app/auth/forgot-password/page.tsx
  app/auth/sign-in/page.tsx
  app/auth/sign-up/page.tsx
Labels: enhancement, Sprint 8

#394 nsc-events-nextjs-8-393_add_user_details_to_profile_page
  app/profile/page.tsx
  components/CurrentUserCard.tsx
  components/ViewMyEventsGetter.tsx
  utility/userUtils.ts
Labels: Sprint 8

#424 nsc-nextjs-08-423-add-dark-light-mode
  app/layout.tsx
  app/theme/providers.tsx
  app/theme/themes.tsx
  components/Navbar.tsx
  components/ThemeToggle.tsx
  components/WrapperDiv.tsx
  package-lock.json
  package.json
Labels: Sprint 8

#435 nsc-events-nextjs_8_428_event-background-images
  app/event-detail/page.tsx
Labels: enhancement, Sprint 8

#425 nsc-events-nextjs-7-404-unit-test-sign-up-page
  app/auth/sign-up/page.tsx
  tests/unit/signup.test.tsx
Labels: Sprint 7

#431 nsc-events-nextjs_8_430_update-useeventform-fetch-call
  hooks/useEventForm.tsx
Labels: bug, Sprint 8

#434 nsc-events-nextjs_8_433_add-and-update-eventMeetingUrl
  app/create-event/page.tsx
  components/EditDialog.tsx
  components/ViewMoreDetailsDialog.tsx
  hooks/useEventForm.tsx
  models/activity.ts
  models/activityAutofill.ts
  models/activityDatabase.ts
Labels: bug, Sprint 8

#429 nsc-events-nextjs_8_427_edit-dialog-arrows
  app/event-detail/page.tsx
  components/EditDialog.tsx
Labels: enhancement, Sprint 8

#403 NSC-Events-Nextjs-7-402-unit-test-sign-in-page
  package-lock.json
  package.json
  tests/unit/signin.test.tsx
Labels: Sprint 7

#441 nsc-events-8-bug-440-improper-event-loading
  app/event-detail/page.tsx
  components/ArchiveDialog.tsx
  hooks/useEditForm.tsx
  hooks/useEventForm.tsx
  utility/queries.ts
Labels: bug, Sprint 8

#439 nsc-events-8-409-implement-material-ui
  app/admin/page.tsx
  app/archived-events/page.tsx
  app/creator/page.tsx
  app/home.module.css
  app/my-events/page.tsx
  app/page.tsx
  components/ViewMyEventsGetter.tsx
  next.config.js
Labels: Sprint 8

#418 nsc-events-nextjs_7_continuous-deployment_add-ssh-workflow
  .github/workflows/ssh.yml
Labels: Sprint 7

#444 nsc-events-nextjs_8_443_update-theme-styling
  app/archived-events/page.tsx
  app/auth/change-password/page.tsx
  app/auth/forgot-password/page.tsx
  app/auth/sign-in/page.tsx
  app/auth/sign-up/page.tsx
  app/create-event/page.tsx
  app/edit-user-role-page/page.tsx
  app/event-detail/page.tsx
  app/home.module.css
  app/logo.png
  app/my-events/page.tsx
  app/page.tsx
  app/theme/themes.tsx
  components/AuthProfileMenu.tsx
  components/EditUserRoleDialog.tsx
  components/EventCard.tsx
  components/Navbar.tsx
  components/UpcomingEvent.tsx
  hooks/useAuth.tsx
  public/images/blue_nsc_logo.png
  public/images/blue_vertical_nsc_logo.png
  public/images/white_nsc_logo.png
  public/images/white_vertical_nsc_logo.png
Labels: Sprint 8

#450 nsc-events-nextjs_8_449_replace-favicon
  app/favicon.ico
  app/layout.tsx
Labels: enhancement, Sprint 8

#446 nsc-events-nextjs-8-445-unarchive-events-button-and-functionality
  app/event-detail/page.tsx
  components/ArchiveDialog.tsx
  components/HomeEventGetter.tsx
  components/ViewMoreDetailsDialog.tsx
Labels: Sprint 8

#438 NSC_NextJS_407_Edit_User_Role_Unit_Test
  tests/unit/creator.test.tsx
  tests/unit/editUserRole.test.tsx
  tests/unit/math.test.ts
Labels: Sprint 8

#452 nsc-events-nextjs_8_351_update-styling-of-confirmation-messages
  app/event-detail/page.tsx
  components/ArchiveDialog.tsx
  components/AttendDialog.tsx
Labels: Sprint 8

#454 nsc-events-nextjs_8_453_refactor-text-border-to-be-visible
  components/InputFields.tsx
Labels: bug

#442 nsc-events-nextjs_7_432_role-authorized-archived-events-2
  app/archived-events/page.tsx
  components/UnauthorizedPages.tsx
  package-lock.json
  package.json
Labels: Sprint 7

#415 nsc-events-nextjs-fixing-responsive-UI-01
  app/my-events/page.tsx
  components/DrawerComp.tsx
  components/EventCard.tsx
  components/Navbar.tsx
  components/ViewMyEventsGetter.tsx
Labels: enhancement, Sprint 8

#459 nsc-events_nextjs _ 07 _ 416 _ continuous-deployment
  .github/workflows/ssh.yml
  app/auth/sign-in/page.tsx
Labels: Sprint 7

#389 nsc-events-nextjs-293-arrow-icon-functionality-01
  app/event-detail/page.tsx
  components/ViewMyEventsGetter.tsx
Labels: enhancement, Sprint 7

#460 nsc-events-nextjs_8_392_change-password-sign-out
  app/auth/change-password/page.tsx
Labels: bug, Sprint 8

#481 nsc-events-nextjs-7-397-clean-up-error-msgs
  app/create-event/page.tsx
  hooks/useEventForm.tsx
  utility/validateFormData.tsx
Labels: Sprint 7
