Repository SeattleColleges/nsc-events-nextjs, pull requests merged in 2024-07, with the labels that each got.

#483 nsc-events-nextjs_7_482_admin-role-authorization
  app/admin/page.tsx
  app/edit-user-role-page/page.tsx
  jest.config.js
  tests/unit/admin.test.tsx
  tests/unit/editUserRole.test.tsx
Labels: enhancement, Sprint 7

#464 nsc_event_8_437_blue-logo-dropdown-with-signet-and-myAccount
  components/DrawerComp.tsx
  components/Navbar.tsx
Labels: Sprint 8

#480 nsc-events-08-436-bug-create-new-event-required-field-logic-fix
  hooks/useEventForm.tsx
  utility/validateFormData.tsx
Labels: bug, Sprint 8

#492 nsc-events-nextjs_9_490_user-dropdown-profile-click
  components/DrawerComp.tsx
  components/Navbar.tsx
Labels: enhancement, Sprint 9

#497 nsc-events-nextjs_9_493_change-user-details
  app/profile/page.tsx
  components/CurrentUserCard.tsx
  components/EditUserDetailsDialog.tsx
Labels: enhancement, Sprint 9

#494 nsc-events-nextjs_9_491_update-buttons-in-edit-user-role-dialog
  components/EditUserRoleDialog.tsx
  components/UserCard.tsx
Labels: Sprint 9

#503 nsc-events-nextjs_9_502_disable-save-dialog-buttons
  components/EditDialog.tsx
  components/EditUserRoleDialog.tsx
Labels: enhancement, Sprint 9

#506 nsc-events-nextjs_9_499_responsive-ui-for-my-events-and-archived-events-pages
  app/archived-events/page.tsx
  app/my-events/page.tsx
  components/EventCard.tsx
  components/ViewMyEventsGetter.tsx
Labels: Sprint 9

#505 nsc-events-nextjs_9_504_creator-page-responsive-ui
  app/creator/page.tsx
Labels: enhancement, Sprint 9

#500 nsc-events-nextjs_9_498_admin-page-responsive-ui
  app/admin/page.tsx
Labels: enhancement, Sprint 9

#511 nsc-events-next_9_507_edit-user-role-profile-page-responsive-ui
  app/edit-user-role-page/page.tsx
  app/profile/page.tsx
  components/UserCard.tsx
Labels: enhancement, Sprint 9

#514 nsc-events-nextjs_9_501_url_errors_when_editing_event
  utility/validateFormData.tsx
Labels: Sprint 9

#516 nsc-events-nextjs_9_509-responsive-ui-for-event-detail-page
  app/event-detail/page.tsx
Labels: Sprint 9

#519 nsc-events-nextjs-9-508-archived-event-detail-page-doesnt-load
  app/archived-events/page.tsx
  app/event-detail/page.tsx
  components/EventCard.tsx
  components/HomeEventGetter.tsx
  components/ViewMyEventsGetter.tsx
  utility/queries.ts
Labels: bug

#521 nsc-events-nextjs-9-510-make-sign-up-consistent
  app/auth/sign-up/page.tsx
Labels: Sprint 9

#520 nsc-events-nextjs_9_515_refactor-event-description-field
  app/create-event/page.tsx
  components/EditDialog.tsx
Labels: bug, Sprint 9

#517 nsc-events-nextjs_9_513_sign-up-responsive-ui
  app/auth/sign-up/page.tsx
Labels: enhancement, Sprint 9

#524 nsc-events-9-bug-518-invalid-start-and-end-times
  components/EditDialog.tsx
Labels: bug

#527 nsc-events-nextjs_9_526_improve-ui-and-add-headings
  app/admin/page.tsx
  app/auth/sign-in/page.tsx
  app/auth/sign-up/page.tsx
  app/create-event/page.tsx
  app/creator/page.tsx
  app/theme/themes.tsx
Labels: Sprint 9

#532 nsc-events-nextjs_9_528_responsive-ui-for-home-page
  app/admin/admin-page.module.css
  app/admin/page.tsx
  app/archived-events/page.tsx
  app/auth/forgot-password/forgot-password-page.module.css
  app/auth/sign-in/signin-page.module.css
  app/create-event/page.tsx
  app/creator/creator-page.module.css
  app/creator/page.tsx
  app/event-detail/page.tsx
  app/home.module.css
  app/my-events/page.tsx
  app/page.tsx
  app/theme.ts
  components/EventCard.tsx
  components/HomeEventGetter.tsx
  components/UpcomingEvent.tsx
  components/ViewMyEventsGetter.tsx
  public/images/google_play.png
  styles/Home.module.css
  styles/globals.css
Labels: Sprint 9

#541 nsc-events-nextjs_9_533_missing-arrows-after-clicking-detail
  components/UpcomingEvent.tsx
Labels: bug, Sprint 9

#538 nsc-events-nextjs_9_537_signin-change-forgot-pw-responsive-ui
  app/auth/change-password/page.tsx
  app/auth/forgot-password/page.tsx
  app/auth/sign-in/page.tsx
Labels: enhancement, Sprint 9

#543 nsc-events-nextjs-9-542-remove-errors-create-event-btn
  app/create-event/page.tsx
Labels: Sprint 9

#545 nsc-events-nextjs-9-544-event-note-optional-visible-only-createdby-admin
  app/event-detail/page.tsx
  components/ViewMoreDetailsDialog.tsx
Labels: Sprint 9

#540 nsc-events-nextjs_9_539_add-confirmation-message-on-forgot-password-page
  app/auth/forgot-password/page.tsx
Labels: Sprint 9

#550 nsc-events-nextjs_10_549_hide-isArchived-and-attendanceCount-fields
  components/ViewMoreDetailsDialog.tsx
Labels: Sprint 10

#487 nsc-events-nextjs_8_486_unit-testing-01
  next.config.js
  tests/unit/admin.test.tsx
Labels: good first issue

#553 nsc-events-nextjs-10-548-home-page-filter-events-by-tag
  app/create-event/page.tsx
  components/HomeEventGetter.tsx
  utility/queries.ts
  utility/tags.ts
Labels: enhancement
