Repository SeattleColleges/nsc-events-nextjs, pull requests merged in 2024-04, with the labels that each got.

#249 nsc-events-nextjs-248-fix-nextjs-templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/pull_request.md
  .github/ISSUE_TEMPLATE/user_story.md
Labels: bug

#255 nsc-events-nextjs-253-route-user-to-homepage-on-sign-in
  app/auth/sign-in/page.tsx
Labels: Sprint 5

#260 nsc_events_nextjs_1_250_admin_route_view_all_events_to_home_page
  app/admin/page.tsx
Labels: Sprint 1

#261 nsc_events_nextjs_1_250_creator_route_view_all_events_to_home_page
  app/creator/page.tsx
Labels: Sprint 1

#275 nsc-events-nextjs-5-258_app_crashes_when_refreshing_event_detail_page
  app/event-detail/page.tsx
Labels: bug, Sprint 5

#277 nsc-events-nextjs-5-264-view-my-events-page
  app/admin/page.tsx
  app/creator/page.tsx
  app/my-events/page.tsx
  components/ViewMyEventsGetter.tsx
Labels: Sprint 5

#257 nsc-events-nextjs-256-archive-functionality
  app/event-detail/page.tsx
  components/ArchiveDialog.tsx
  components/HomeEventGetter.tsx
  components/UpcomingEvent.tsx
  models/activityDatabase.ts
Labels: Sprint 5

#280 nscevents-nextjs-chore-remove-unused-authentication-next-server
  app/api/auth/[...nextauth]/route.ts
  app/api/auth/users/route.ts
Labels: Sprint 5

#281 nsc-events-nextjs_5_273_testing-processing-02
  .github/workflows/ci.yml
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  tests/unit/admin.test.tsx
Labels: Sprint 5
