Repository SeattleColleges/nsc-events-nextjs, pull requests merged in 2024-05, with the labels that each got.

#282 nsc-events-nextjs-5-247-attend-event-functionality
  app/event-detail/page.tsx
  components/AttendDialog.tsx
Labels: Sprint 5

#299 nsc-events-nextjs_6_297_archived-events-placeholder-page
  app/admin/page.tsx
  app/archived-events/page.tsx
  app/creator/page.tsx
Labels: enhancement, Sprint 6

#316 nsc_events_nextjs_6_309_create_event_page_text_field_width
  app/create-event/page.tsx
  components/TagSelector.tsx
Labels: Sprint 6

#313 nsc-events-nextjs_6_314_qa-testing-for-creator-page
  tests/unit/creator.test.tsx
Labels: Sprint 6

#302 nsc-events-nextjs-6-288-home-page-events-pagination
  components/HomeEventGetter.tsx
  components/UpcomingEvent.tsx
  utility/queries.ts
Labels: Sprint 6

#339 nsc-events-nextjs-6-337-fix-incorrect-date-format-logic
  utility/dateUtils.ts
Labels: bug

#319 nsc-events-nextjs-5-318-create-page-and-components
  app/edit-user-role-page/page.tsx
  components/EditUserRoleDialog.tsx
  components/UserCard.tsx
Labels: Sprint 5

#345 Create-Event Page Feature: Allow custom event tags to be created
  app/create-event/page.tsx
  components/TagSelector.tsx
Labels: Sprint 6

#361 nsc-events-nextjs_7_359_edit-messages-redirect
  app/event-detail/page.tsx
  components/ArchiveDialog.tsx
  components/AttendDialog.tsx
Labels: enhancement, Sprint 7

#363 nsc-events-nextjs_7_360_creator-access
  app/event-detail/page.tsx
  components/ArchiveDialog.tsx
Labels: enhancement, Sprint 7

#366 nsc-events-nextjs-7-351-display-archived-events
  app/archived-events/page.tsx
  components/ArchiveDialog.tsx
  utility/queries.ts
Labels: Sprint 7

#365 nsc-events-nextjs_7_376_role-authorize-create-event
  app/create-event/page.tsx
  hooks/useAuth.tsx
  next.config.js
  package-lock.json
  package.json
Labels: Sprint 7

#364 nsc-events-nextjs_7_295_arrow_icons
  app/event-detail/page.tsx
Labels: enhancement, help wanted, Sprint 7

#378 nsc-events-nextjs-7-381-my-events-page-pagination
  app/event-detail/page.tsx
  app/my-events/page.tsx
  components/ArchiveDialog.tsx
  components/ViewMyEventsGetter.tsx
  hooks/useEditForm.tsx
  hooks/useEventForm.tsx
  utility/queries.ts
Labels: Sprint 7
