Repository SeattleColleges/nsc-events-nextjs, pull requests merged in 2024-02, with the labels that each got.

#161 Refactoring: Implement Material UI in sign-up-page
  app/auth/sign-up/page.tsx
  app/showpassword.png
Labels: Sprint 2

#158 nsc-nextjs-02-156-sign_in_function
  app/auth/sign-in/page.tsx
Labels: Sprint 2

#160 nsc-nextjs-01-143-route-event-to-event-detail
  app/event-detail/page.tsx
  components/EventGetter.tsx
  models/activityDatabase.ts
Labels: Sprint 1

#168 nsc-events-nextjs_2_167_creator-page-buttons
  app/creator/creator-page.module.css
  app/creator/page.tsx
Labels: enhancement, Sprint 2

#165 nsc-events-nextjs_2_164_admin-page-button
  app/admin/admin-page.module.css
  app/admin/page.tsx
Labels: enhancement, Sprint 2

#170 nsc-events-nextjs-2-169-create-templates-for-nextjs
  .github/issue.md
  .github/pull_request.md
  .github/user_story.md
Labels: Sprint 2

#173 nsc-events-nextjs-2-171-add-front-matter-to-nextjs
  .github/issue.md
  .github/pull_request.md
  .github/user_story.md
Labels: Sprint 2

#155 nsc-events-nextjs-01-163-Add EventDate DatePicker, eventStartTime Picker and eventEndTime Picker
  app/create-event/page.tsx
  components/ImagePicker.tsx
  components/InputFields.tsx
  hooks/useDateTimeSelection.tsx
  hooks/useEventForm.tsx
  models/activity.ts
  package-lock.json
  package.json
  utility/validateFormData.tsx
Labels: enhancement, Sprint 1

#175 nsc-events-nextjs_2_162_refactor-sign-in-page-and-enhance-UI-consistency
  app/auth/sign-in/page.tsx
  app/auth/sign-up/page.tsx
  app/layout.tsx
  app/theme.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement, Sprint 2

#178 Delete signup-page.module.css
  app/auth/sign-up/signup-page.module.css
Labels: USER STORY

#181 Refactor 177 signup page move validation
  app/auth/sign-up/page.tsx
  app/auth/sign-up/validateSignUp.tsx
Labels: enhancement

#191 nsc-events-nextjs_2_183-move-api-call-to-separate-utility-file
  app/auth/sign-up/page.tsx
  app/auth/sign-up/signupApi.tsx
Labels: enhancement

#200 nsc-events-nextjs-3-197-solid-background-color
  app/globals.css
  app/layout.tsx
  app/theme.ts
Labels: enhancement, Sprint 3

#201 nsc-events-nextjs-3-198-and-199-standardize-button-colors-and-input-field-styles
  app/auth/forgot-password/page.tsx
  app/auth/sign-in/page.tsx
  app/auth/sign-up/page.tsx
  app/theme.ts
  components/InputFields.tsx
Labels: enhancement, Sprint 3

#192 nsc-events-nextjs_2_184_update-page.tsx
  app/auth/sign-up/page.tsx
Labels: enhancement

#195 nsc-events-nextjs-3-194-add-files-to-nextjs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/pull_request.md
  .github/ISSUE_TEMPLATE/user_story.md
Labels: Sprint 3

#211 nsc-events-nextjs_3_210_route-to-login-page
  app/auth/sign-up/page.tsx
Labels: enhancement, Sprint 3

#203 Home Page: Conditionally render Intro Screen
  app/auth/sign-in/page.tsx
  app/page.tsx
Labels: enhancement

#217 nsc-events-nextjs_3_212_add-pronouns-field
  app/auth/sign-up/page.tsx
Labels: enhancement, Sprint 3

#213 nsc-events-nextjs_3_208_adjust-event-details-card-size
  app/event-detail/page.tsx
Labels: Sprint 3

#216 nsc-events-nextjs_3_205_refactor-create-event-page
  app/create-event/page.tsx
  app/theme.ts
  components/TagSelector.tsx
Labels: enhancement

#221 nsc-events-nextjs-222-refactor-create-event-page
  app/create-event/page.tsx
  models/activity.ts
  package-lock.json
  package.json
Labels: enhancement, Sprint 3
