Repository SeattleColleges/nsc-events-nextjs, pull requests merged in 2024-01, with the labels that each got.

#124 nsc-events-nextjs-01-118-admin-page-creation
  app/admin/page.tsx
  app/auth/sign-in/page.tsx
Labels: Sprint 1

#134 nsc-nextjs-bug-131-fix-ci-on-pull-request-01
  .github/workflows/on-new-branch.yml
  .github/workflows/on-pull-request.yml
  components/Navbar.tsx
Labels: bug

#120 nsc-events-nextjs-1-122-add-requested-ui-features
  app/NorthSeattleLogo.png
  app/auth/sign-up/page.tsx
  app/auth/sign-up/signup-page.module.css
  app/showpassword.png
  components/InputFields.tsx
  package-lock.json
  package.json
Labels: Sprint 1

#121 nsc-events-nextjs-01-119-modify-frontend-port
  .env.sample
  components/Navbar.tsx
Labels: Sprint 1

#127 nsc-events-nextjs-1-130-update-react-query-package
  components/Navbar.tsx
  package-lock.json
  package.json
Labels: Sprint 1

#132 nsc-events-nextjs-01-133-creator-page-creation
  app/creator/page.tsx
Labels: Sprint 1

#128 nsc-events-nextjs-1-126-add-material-ui-icons-and-roboto-font
  package-lock.json
  package.json
  styles/globals.css
Labels: dependencies

#137 Bug: README update port to 8080
  README.md
Labels: bug

#146 nsc-events-nextjs-1-145-add-remaining-fields
  app/create-event/page.tsx
  app/globals.css
  styles/globals.css
Labels: Sprint 1

#135 nsc-events-nextjs-1-142-refactor-navigation-to-include-material-ui-drawer
  components/DrawerComp.tsx
  components/Navbar.tsx
Labels: Sprint 1, USER STORY

#149 nsc-events-nextjs-01-139-event-detail-page
  app/create-event/page.tsx
  app/event-detail/page.tsx
  package-lock.json
  package.json
Labels: Sprint 1

#153 Refactoring components and pages for Material UI: Implement Material UI in InputFields.tsx #152
  components/InputFields.tsx
Labels: enhancement, Sprint 2
