Repository SeattleColleges/nsc-events-nextjs, pull requests merged in 2025-01, with the labels that each got.

#598 nsc_events_nextjs_596_merged_github_actions
  .github/workflows/auto-assign-issues.yml
  .github/workflows/on-new-issue.yml
Labels: enhancement

#592 nsc-events-nextjs_14_570_add-document-field-to-more-details
  components/ViewMoreDetailsDialog.tsx
Labels: Sprint 14

#601 nsc-events-nextjs _15_600_post_issue_smartsheet
  .github/workflows/on-pull-request.yml
  post-issue-smartsheet.py
Labels: enhancement

#607 nsc-events-nextjs_16_604_footer
  app/layout.tsx
  components/Footer.tsx
Labels: Sprint 16
