Repository SeattleColleges/nsc-events-nextjs, pull requests merged in 2025-06, with the labels that each got.

#663 nsc-events-nextjs_22_658_event-display
  app/archived-events/page.tsx
  app/profile/components/AttendedEvents.tsx
  app/profile/components/UserContent.tsx
  app/profile/page.tsx
  components/AttendDialog.tsx
  components/HomeEventsCard.tsx
Labels: Sprint 22

#686 nsc-events-nextjs_23_685-bug-event-card-grid-centering
  app/page.tsx
  components/HomeEventsCard.tsx
  components/HomeEventsList.tsx
  package-lock.json
Labels: bug

#683 nsc-events-nextjs_23_682_Removed_the_bio/affiliations_section_of_the_profile page
  app/profile/components/UserContent.tsx
  app/profile/components/UserHeader.tsx
Labels: enhancement

#691 nsc-events-nextjs _24_690_fixed_height_sizing_on_image_tied_to_event
  components/HomeEventsCard.tsx
Labels: bug

#689 nsc-events-nextjs_24_688_route-event-cards-to-event-detail
  app/profile/components/AttendedEvents.tsx
Labels: enhancement, Sprint 24

#696 fix bug where coverPhoto has to be non empty to see the 'Edit Cover Photo' button
  app/event-detail/page.tsx
Labels: bug

#681 678 update date and time only
  components/EditDialog.tsx
  hooks/useEditForm.tsx
Labels: bug, Sprint 23

#684 nsc-events-nextjs_23_679_allow-everyone-to-see-attendee-counts
  app/event-detail/page.tsx
  components/AttendDialog.tsx
Labels: enhancement

#693 nsc-events-nextjs_24_692_Added_date_with_proper_formatting
  components/HomeEventsCard.tsx
Labels: enhancement

#697 nsc-events-nextjs_24_687-select-custom-tags-by-default
  app/create-event/page.tsx
Labels: enhancement, Sprint 24
