Repository SeattleColleges/nsc-events-nextjs, pull requests merged in 2025-03, with the labels that each got.

#621 nsc-events-nextjs_17_613_footer02
  components/Footer.tsx
Labels: bug, Sprint 17

#631 nsc-events_nextjs_19_626_profile-page-rework
  app/profile/components/CurrentUserCard.tsx
  app/profile/components/EditUserDetailsDialog.tsx
  app/profile/components/UserContent.tsx
  app/profile/components/UserHeader.tsx
  app/profile/components/UserSideBar.tsx
  app/profile/page.tsx
Labels: enhancement, Sprint 19

#632 Revert "nsc-events_nextjs_19_626_profile-page-rework"
  app/profile/components/UserContent.tsx
  app/profile/components/UserHeader.tsx
  app/profile/components/UserSideBar.tsx
  app/profile/page.tsx
  components/CurrentUserCard.tsx
  components/EditUserDetailsDialog.tsx
Labels: enhancement, Sprint 19

#627 nsc-events-nextjs_18_619_add-dropdown-box-to-user-management
  app/edit-user-role-page/components/UserTable.tsx
  app/edit-user-role-page/page.tsx
Labels: Sprint 18

#638 highlight and gray the toggle theme icon on mouse hover
  components/Navbar.tsx
  components/ThemeToggle.tsx
Labels: enhancement

#639 nsc-events-nextjs_20_636_modify-textfield-CSS-user-management-page
  app/edit-user-role-page/page.tsx
Labels: Sprint 20
