Repository SeattleColleges/nsc-events-nextjs, pull requests merged in 2025-05, with the labels that each got.

#656 nsc-events-nextjs_22_655_bug_input-labels-darkmode
  app/edit-user-role-page/page.tsx
Labels: bug

#653 nsc-events-nextjs_20_651_bug-fix-overlap-style-issue-homeeventcard
  app/page.tsx
  components/HomeEventCard.tsx
  components/HomeEventsCard.tsx
  components/HomeEventsList.tsx
  package-lock.json
Labels: Sprint 20

#662 Attendees view for admin
  app/event-detail/page.tsx
  components/AttendDialog.tsx
  components/ViewAttendeesDialog.tsx
  components/ViewMoreDetailsDialog.tsx
  types/attendee.ts
Labels: enhancement

#649 nsc-events-nextjs_22_648_Implement_the_ability_to_"Un-Attend"_an_event
  app/event-detail/page.tsx
  components/AttendDialog.tsx
  utility/queries.ts
Labels: enhancement

#635 nsc-events-nextjs_19_633_implement-my-created-events
  app/admin/page.tsx
  app/creator/page.tsx
  app/my-created-events/components/DateFilter.module.css
  app/my-created-events/components/DateFilter.tsx
  app/my-created-events/components/EventCard2.module.css
  app/my-created-events/components/EventCard2.tsx
  app/my-created-events/components/SearchBar.tsx
  app/my-created-events/page.tsx
  tests/unit/creator.test.tsx
Labels: enhancement

#674 nsc-events-nextjs_23_671_remove_staging
  .github/workflows/on-pull-request.yml
  .github/workflows/sync-staging.yml
Labels: Sprint 23

#669 nsc-events-nextjs_22_652_modfiy-event-model-properties-frontend
  app/create-event/page.tsx
  hooks/useEventForm.tsx
  utility/validateFormData.tsx
Labels: Sprint 22

#670 nsc-events-nextjs_23_668_event_cover_photo_dialog_upload
  app/event-detail/page.tsx
  components/CoverPhotoDialog.tsx
Labels: Sprint 23

#676 nsc-events-nextjs_24_673_add-user-role-display-profile-page
  app/profile/components/EditUserDetailsDialog.tsx
  app/profile/components/UserHeader.tsx
  app/profile/page.tsx
Labels: Sprint 24

#675 nsc-events-nextjs_23_672_creators-can-see-attendees
  app/event-detail/page.tsx
Labels: enhancement, Sprint 23
