Repository SeattleColleges/nsc-events-nextjs, pull requests merged in 2025-04, with the labels that each got.

#634 nsc-events_nextjs_19_626_profile-page-rework
  app/profile/components/EditUserDetailsDialog.tsx
  app/profile/components/UserContent.tsx
  app/profile/components/UserHeader.tsx
  app/profile/components/UserSideBar.tsx
  app/profile/page.tsx
  components/CurrentUserCard.tsx
  context/UserContext.tsx
Labels: enhancement, Sprint 19

#629 Redesigning NSC Events Homepage
  .vscode/settings.json
  app/globals.css
  app/page.tsx
  components/EventCard.tsx
  components/EventGetter.tsx
  components/HomeEventCard.tsx
  components/HomeEvents.tsx
  components/LoginWindow.tsx
  components/UpcomingEvent.tsx
  public/images/north-seattle-tree-frogs.png
Labels: enhancement

#650 nsc-events-nextjs_21_643_fix-load-more-events
  app/page.tsx
  utility/queries.ts
Labels: Sprint 21

#647 Upgrade to MUI v7 and refactor navbar layout
  app/admin/page.tsx
  app/archived-events/page.tsx
  app/creator/page.tsx
  app/event-detail/page.tsx
  app/page.tsx
  components/EventCard.tsx
  components/EventGetter.tsx
  components/Footer.tsx
  components/HomeEvents.tsx
  components/Navbar.tsx
  components/UpcomingEvent.tsx
  components/ViewMyEventsGetter.tsx
  package-lock.json
  package.json
Labels: Sprint 20
